#!/usr/bin/env node
// Generated by next-codex-workflow-kit
import { spawnSync } from "node:child_process";
import process from "node:process";

const result = spawnSync(process.execPath, ["scripts/verify-agent-workflow.mjs"], {
  stdio: "inherit"
});

process.exitCode = result.status ?? 1;
