// Generated by next-codex-workflow-kit
module.exports = {
  ci: {
    collect: {
      numberOfRuns: 1,
      url: [
  "/"
],
      startServerCommand: "pnpm start",
      startServerReadyPattern: "ready",
      settings: {
        chromeFlags: "--headless=new"
      }
    },
    assert: {
      assertions: {
        "categories:performance": ["warn", { "minScore": 0.8 }]
      }
    },
    upload: {
      target: "filesystem",
      outputDir: ".lighthouseci"
    }
  },
  workflow: {
    buildCommand: "pnpm build",
    startCommand: "pnpm start"
  }
};
